name: gplus-quickstart-dart
description: This quick-start app is built in Dart and lets you get started with the Google+ platform in a few minutes.
version: 0.0.1
author: Gerwin Sturm <scarygami@gmail.com>
homepage: https://github.com/Scarygami/gplus-quickstart-dart

dependencies:
  browser: any
  google_plus_v1_api: any
